services:
  - type: web
    name: my-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: BROWSERLESS_URL
        value: https://chrome.browserless.io
      - key: BROWSERLESS_TOKEN
        sync: false  # This will be set manually in Render dashboard
      - key: MAX_TEXT_LENGTH
        value: 500
      - key: API_TIMEOUT
        value: 120
